apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-ops-pc
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-ops-pc
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 200
      serviceAccountName: dev-ops-pc-sa
      containers:
        - name: dev-ops-pc-cont
          image: cdocregdes.pronaca.com/presentacion/dev-ops-pc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: "1Gi"
            limits:
              cpu: 250m
              memory: "1Gi"
      imagePullSecrets:
      - name: registry-private
